version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-server
    ports:
      - "8080:8080"
      - "40000:40000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: [ "dlv", "debug", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient", "./main.go" ]

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: [ "redis-server" ]
